"""Move types, legal-move generation, and safe-auto-foundation logic."""

from __future__ import annotations

from dataclasses import dataclass
from enum import IntEnum

from solitaire_solver.cards import Card, Rank, Suit
from solitaire_solver.state import GameState, UndoToken


class MoveType(IntEnum):
    DRAW = 1
    RECYCLE = 2
    WASTE_TO_FOUNDATION = 3
    WASTE_TO_TABLEAU = 4
    TABLEAU_TO_FOUNDATION = 5
    TABLEAU_TO_TABLEAU = 6
    FLIP = 7  # synthetic; not generated by search, emitted in output


@dataclass(frozen=True, slots=True)
class Move:
    mtype: MoveType
    src_pile: int = -1      # for TABLEAU_* moves
    dst_pile: int = -1      # for *_TO_TABLEAU moves
    count: int = 1          # for TABLEAU_TO_TABLEAU
    card: Card | None = None           # primary card (for output/debug)
    revealed_card: Card | None = None  # filled in after apply if a flip occurred


# ---------- Legal move generation ----------


def is_safe_to_foundation(state: GameState, card: Card) -> bool:
    """Thoughtful-safe rule: aces/2s always safe; else both opposite-color
    foundations are at rank >= card.rank - 1.
    """
    r = int(card.rank)
    if r <= 2:
        return True
    if card.color == 0:  # black -> opposite = red = hearts, diamonds
        return (
            state.foundations[int(Suit.HEARTS)] >= r - 1
            and state.foundations[int(Suit.DIAMONDS)] >= r - 1
        )
    else:
        return (
            state.foundations[int(Suit.SPADES)] >= r - 1
            and state.foundations[int(Suit.CLUBS)] >= r - 1
        )


def auto_play_safe(state: GameState) -> list[tuple[Move, UndoToken]]:
    """Apply every safe tableau->foundation and waste->foundation move to
    fixpoint. Returns the ordered list of (move, undo_token) so the caller can
    undo if desired.
    """
    applied: list[tuple[Move, UndoToken]] = []
    progress = True
    while progress:
        progress = False
        # Tableau tops
        for i in range(7):
            fu = state.tableau_face_up[i]
            if not fu:
                continue
            top = fu[-1]
            if state.foundations[int(top.suit)] + 1 == int(top.rank) and is_safe_to_foundation(state, top):
                tok = state.apply_tableau_to_foundation(i)
                move = Move(
                    mtype=MoveType.TABLEAU_TO_FOUNDATION,
                    src_pile=i,
                    card=top,
                    revealed_card=tok.src_flipped_card,
                )
                applied.append((move, tok))
                progress = True
                break
        else:
            # Waste top
            if state.cursor >= 0:
                top = state.deck[state.cursor]
                if state.foundations[int(top.suit)] + 1 == int(top.rank) and is_safe_to_foundation(state, top):
                    tok = state.apply_waste_to_foundation()
                    move = Move(mtype=MoveType.WASTE_TO_FOUNDATION, card=top)
                    applied.append((move, tok))
                    progress = True
    return applied


def undo_all(state: GameState, applied: list[tuple[Move, UndoToken]]) -> None:
    for _, tok in reversed(applied):
        state.undo(tok)


def legal_moves(state: GameState) -> list[Move]:
    """Enumerate non-redundant legal moves from ``state`` in search order
    (higher-priority moves first)."""
    moves: list[Move] = []

    # Gather face-up tops and run info.
    # Tableau -> foundation
    for i in range(7):
        fu = state.tableau_face_up[i]
        if not fu:
            continue
        top = fu[-1]
        if state.foundations[int(top.suit)] + 1 == int(top.rank):
            moves.append(Move(mtype=MoveType.TABLEAU_TO_FOUNDATION, src_pile=i, card=top))

    # Waste -> foundation
    if state.cursor >= 0:
        top = state.deck[state.cursor]
        if state.foundations[int(top.suit)] + 1 == int(top.rank):
            moves.append(Move(mtype=MoveType.WASTE_TO_FOUNDATION, card=top))

    # Tableau -> tableau
    for src in range(7):
        fu_src = state.tableau_face_up[src]
        if not fu_src:
            continue
        fd_src_len = len(state.tableau_face_down[src])
        n = len(fu_src)
        for k in range(1, n + 1):
            bottom = fu_src[-k]
            # Moving ALL face-up cards from an already-empty-facedown pile to
            # another empty pile is useless (just swaps empty slots).
            full_move = k == n
            for dst in range(7):
                if dst == src:
                    continue
                fu_dst = state.tableau_face_up[dst]
                if fu_dst:
                    top_dst = fu_dst[-1]
                    if (
                        int(top_dst.rank) == int(bottom.rank) + 1
                        and top_dst.color != bottom.color
                    ):
                        moves.append(
                            Move(
                                mtype=MoveType.TABLEAU_TO_TABLEAU,
                                src_pile=src,
                                dst_pile=dst,
                                count=k,
                                card=bottom,
                            )
                        )
                else:
                    # dst empty: only Kings. Also prune useless empty-to-empty King moves.
                    if int(bottom.rank) != 13:
                        continue
                    if full_move and fd_src_len == 0:
                        continue  # empty-to-empty shuffle of a King, no progress
                    moves.append(
                        Move(
                            mtype=MoveType.TABLEAU_TO_TABLEAU,
                            src_pile=src,
                            dst_pile=dst,
                            count=k,
                            card=bottom,
                        )
                    )

    # Waste -> tableau
    if state.cursor >= 0:
        top = state.deck[state.cursor]
        for dst in range(7):
            fu_dst = state.tableau_face_up[dst]
            if fu_dst:
                top_dst = fu_dst[-1]
                if int(top_dst.rank) == int(top.rank) + 1 and top_dst.color != top.color:
                    moves.append(
                        Move(
                            mtype=MoveType.WASTE_TO_TABLEAU,
                            dst_pile=dst,
                            card=top,
                        )
                    )
            else:
                if int(top.rank) == 13:
                    moves.append(
                        Move(mtype=MoveType.WASTE_TO_TABLEAU, dst_pile=dst, card=top)
                    )

    # Draw / recycle
    if state.stock_has_cards():
        moves.append(Move(mtype=MoveType.DRAW))
    elif state.cursor == len(state.deck) - 1 and len(state.deck) > 0:
        moves.append(Move(mtype=MoveType.RECYCLE))

    moves.sort(key=lambda m: _ordering_key(state, m))
    return moves


def _ordering_key(state: GameState, m: Move) -> tuple:
    """Lower tuple = tried first. First-solution-fast ordering."""
    if m.mtype == MoveType.TABLEAU_TO_FOUNDATION:
        fd = len(state.tableau_face_down[m.src_pile])
        fu_len = len(state.tableau_face_up[m.src_pile])
        reveals = fu_len == 1 and fd > 0
        # Prefer reveals; among reveals prefer piles with more face-down.
        return (0 if reveals else 4, -fd if reveals else 0)
    if m.mtype == MoveType.TABLEAU_TO_TABLEAU:
        fd = len(state.tableau_face_down[m.src_pile])
        fu_len = len(state.tableau_face_up[m.src_pile])
        reveals = m.count == fu_len and fd > 0
        empties_column = m.count == fu_len and fd == 0
        if reveals:
            return (1, -fd, -m.count)
        if empties_column:
            return (3, -m.count)
        return (3, -m.count)
    if m.mtype == MoveType.WASTE_TO_TABLEAU:
        return (2, 0)
    if m.mtype == MoveType.WASTE_TO_FOUNDATION:
        return (4, 0)
    if m.mtype == MoveType.DRAW:
        return (5, 0)
    if m.mtype == MoveType.RECYCLE:
        return (6, 0)
    return (9, 0)


# ---------- Apply via Move dispatch ----------


def apply_move(state: GameState, m: Move) -> UndoToken:
    if m.mtype == MoveType.DRAW:
        return state.apply_draw()
    if m.mtype == MoveType.RECYCLE:
        return state.apply_recycle()
    if m.mtype == MoveType.WASTE_TO_FOUNDATION:
        return state.apply_waste_to_foundation()
    if m.mtype == MoveType.WASTE_TO_TABLEAU:
        return state.apply_waste_to_tableau(m.dst_pile)
    if m.mtype == MoveType.TABLEAU_TO_FOUNDATION:
        return state.apply_tableau_to_foundation(m.src_pile)
    if m.mtype == MoveType.TABLEAU_TO_TABLEAU:
        return state.apply_tableau_to_tableau(m.src_pile, m.dst_pile, m.count)
    raise ValueError(f"unknown move: {m}")


def is_inverse(prev: Move, next_: Move) -> bool:
    """Cheap no-undo prune: forbid the literal inverse of the last move."""
    if prev.mtype == MoveType.TABLEAU_TO_TABLEAU and next_.mtype == MoveType.TABLEAU_TO_TABLEAU:
        return (
            prev.src_pile == next_.dst_pile
            and prev.dst_pile == next_.src_pile
            and prev.count == next_.count
        )
    return False
